[package]
name = "sigmaos-downloader"
version = "0.9.17"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
futures-util.workspace = true
httpdate.workspace = true
nix.workspace = true
rand.workspace = true
reqwest.workspace = true
rustls.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tokio-util.workspace = true
toml_edit.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
